version: '3.8'
services:
  demo-database:
    container_name: multithread-batch-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopass
      - POSTGRES_DB=demo
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  data: { }